openapi: "3.0.1"
info:
  title: "AIMS Data Platform REST API"
  version: "1.0"
  contact:
    name: "AIMS Datacentre"
    email: "adc@aims.gov.au"
    url: "https://www.aims.gov.au"
  license:
    name: "CC BY 3.0"
    url: "https://creativecommons.org/licenses/by/3.0/au/legalcode"
servers:
  - url: "https://api.aims.gov.au/data"
paths:
  /v1.0/10.25845/5c09bf93f315d/parameters:
    get:
      summary: "list of available parameters"
      description: "The list of available parameters such as Wind Speed, see examples [here](https://aims.github.io/data-platform/weather/parameters)"
      tags:
        - weather
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOfParameters"
  /v1.0/10.25845/5c09bf93f315d/series:
    get:
      summary: "list of available data series"
      description: "The list of available data series, see examples [here](https://aims.github.io/data-platform/weather/series).  A data series is a time series dataset on the same parameter at the same location."
      tags:
        - weather
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOfSeries"
  /v1.0/10.25845/5b4eb0f9bb848/sites:
    get:
      summary: "list of available sites"
      description: "The list of available site names, see examples [here](https://aims.github.io/data-platform/temperature-loggers/sites)"
      tags:
        - temperature-loggers
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOfSitesInResults"
  /v1.0/10.25845/5c09bf93f315d/sites:
    get:
      summary: "list of available sites"
      description: "The list of available site names, see examples [here](https://aims.github.io/data-platform/weather/sites)"
      tags:
        - weather
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOfSites"
  /v1.0/10.25845/5b4eb0f9bb848/data:
    get:
      summary: "get data with citation"
      description: "Gets a page of data, with a default 1000 rows"
      tags:
        - temperature-loggers
      parameters:
      - name: "x-api-key"
        in: "header"
        schema:
          type: "string"
          example: "my-api-key"
        description: "Your [AIMS Data Platform API Key](https://aims.github.io/data-platform/key-request)"
      - name: "site-name"
        in: "query"
        schema:
          type: "string"
          example: "Davies Reef"
        description: "A site name, can be found [here](https://aims.github.io/data-platform/temperature-loggers/sites)"
      - name: "from-date"
        in: "query"
        schema:
          type: datetime
          example: "2000-01-01"
        description: "Format YYYY-MM-DDThh:mm:ss"
      - name: "thru-date"
        in: "query"
        schema:
          type: datetime
          example: "2000-01-07"
        description: "Format YYYY-MM-DDThh:mm:ss"
      - name: "min-latitude"
        in: "query"
        schema:
          type: number
          example: -18.0
        description: "Minimum latitude in signed degrees format"
      - name: "max-latitude"
        in: "query"
        schema:
          type: number
          example: -15.0
        description: "Maximim latitude in signed degrees format"
      - name: "min-longitude"
        in: "query"
        schema:
          type: number
          example: 145.0
        description: "Minimum longitude in signed degrees format"
      - name: "max-longitude"
        in: "query"
        schema:
          type: number
          example: 147.6
        description: "Maximum longitude in signed degrees format"
      - name: "size"
        in: "query"
        schema:
          type: integer
          example: 1000
        description: "The maximum number of rows per request"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseWithCitation"
      security:
      - api_key: []
    options:
      summary: "get data with citation - cors support"
      description: "Provides cors header for pre-flight checks"
      tags:
        - temperature-loggers
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /v1.0/10.25845/5c09bf93f315d/data:
    get:
      summary: "get data with citation"
      description: "Gets a page of data"
      tags:
        - weather
      parameters:
      - name: "x-api-key"
        in: "header"
        schema:
          type: "string"
          example: "my-api-key"
        description: "Your [AIMS Data Platform API Key](https://aims.github.io/data-platform/key-request)"
      - name: "site-name"
        in: "query"
        schema:
          type: "string"
          example: "Davies Reef"
        description: "A site name, can be found [here](https://aims.github.io/data-platform/weather/sites)"
      - name: "series"
        in: "query"
        schema:
          type: integer
          example: 73
        description: "A series ID, can be found [here](https://aims.github.io/data-platform/weather/series). A data series is a time series dataset on the same parameter at the same location."
      - name: "parameter"
        in: "query"
        schema:
          type: "string"
          example: "Wind Speed (Scalar avg 10 min)"
        description: "Measured weather parameter name, the available list can be seen [here](https://aims.github.io/data-platform/weather/parameters)"
      - name: "from-date"
        in: "query"
        schema:
          type: datetime
          example: "2018-01-01"
        description: "Format YYYY-MM-DDThh:mm:ss"
      - name: "thru-date"
        in: "query"
        schema:
          type: datetime
          example: "2018-01-07"
        description: "Format YYYY-MM-DDThh:mm:ss"
      - name: "min-latitude"
        in: "query"
        schema:
          type: number
          example: -20.0
        description: "Minumum latitude in signed degrees format"
      - name: "max-latitude"
        in: "query"
        schema:
          type: number
          example: -18.0
        description: "Maximum latitude in signed degrees format"
      - name: "min-longitude"
        in: "query"
        schema:
          type: number
          example: 140.0
        description: "Longitude in signed degrees format"
      - name: "max-longitude"
        in: "query"
        schema:
          type: number
          example: 150.0
        description: "Longitude in signed degrees format"
      - name: "size"
        in: "query"
        schema:
          type: integer
          example: 1000
        description: "The maximum number of rows per request"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WeatherResponseWithCitation"
      security:
      - api_key: []
    options:
      summary: "get data with citation - cors support"
      description: "Provides cors header for pre-flight checks"
      tags:
        - weather
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    WeatherResponseWithCitation:
      title: "Response with Citation"
      type: "object"
      properties:
        citation:
          type: "string"
          description: "Academic citation for the data"
        metadata:
          type: "string"
          description: "Metadata such as URL"
        links:
          type: "array"
          description: "Links associated with dataset"
          items:
            type: "string"
            description: "Link associated with dataset"
        results:
          type: "array"
          description: "The returned data"
          items:
            type: "object"
            properties:
              deployment_id:
                type: "number"
                description: "Deployment ID"
              site_name:
                type: "string"
                description: "The Site where measurement was taken"
              location_name:
                type: "string"
                description: "The location ID where measurement was taken"
              depth:
                type: "number"
                description: "The depth as which measurement was taken"
              latitude:
                type: "number"
                description: "Latitude of measurement"
              longitude:
                type: "number"
                description: "Longitude of measurement"
              parameter:
                type: "string"
                description: "Measurement Type"
              serial_num:
                type: "string"
                description: "Serial number"
              data_id:
                type: "number"
                description: "Data ID"
              time:
                type: "string"
                description: "Time of measurement"
              raw_value:
                type: "number"
                description: "Measured value"
              qc_value:
                type: "number"
                description: "Measured value"
              series_id:
                type: "number"
                description: "Series ID"
              series_name:
                type: "string"
                description: "The name of series"
    Empty:
      title: "Empty Schema"
      type: "object"
    ListOfSeries:
      title: "List of Series"
      type: "array"
      items:
        type: "object"
        properties:
          series_id:
            type: "number"
            description: "Series ID"
          series_name:
            type: "string"
            description: "Series name"
    ListOfParameters:
      title: "List of Parameters"
      type: "array"
      items:
        type: "string"
        description: "The parameter name"
    ListOfSitesInResults:
      title: "List of Sites"
      type: "object"
      properties:
        results:
          type: "array"
          description: "The returned list of sites"
          items:
            type: "string"
            description: "The site name"
    ResponseWithCitation:
      title: "Response with Citation"
      type: "object"
      properties:
        citation:
          type: "string"
          description: "Academic citation for the data"
        metadata:
          type: "string"
          description: "Metadata such as URL"
        results:
          type: "array"
          description: "The returned data"
          items:
            type: "object"
            properties:
              site_name:
                type: "string"
                description: "The Site where measurement was taken"
              location_name:
                type: "string"
                description: "The location ID where measurement was taken"
              depth:
                type: "number"
                description: "The depth as which measurement was taken"
              latitude:
                type: "number"
                description: "Latitude of measurement"
              longitude:
                type: "number"
                description: "Longitude of measurement"
              time:
                type: "string"
                description: "Time of measurement"
              serial_num:
                type: "number"
                description: "Serial number"
              parameter:
                type: "string"
                description: "Measurement Type"
              value:
                type: "number"
                description: "Measured value"
    ListOfSites:
      title: "List of Sites"
      type: "array"
      items:
        type: "string"
        description: "The site name"
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
